name: CI Ubuntu Focal (ANA)

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  run:
    runs-on: ubuntu-20.04
    steps:
    - name: Setup SSH
      uses: MrSquaare/ssh-setup-action@v1
      with:
          host: github.com
          private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Install system dependencies
      shell: bash
      run: |
        mkdir -p ${TMPDIR-/tmp}/build-mc-rtc
        cmake -S ${GITHUB_WORKSPACE} -B ${TMPDIR-/tmp}/build-mc-rtc -DCMAKE_BUILD_TYPE=RelWithDebInfo -DUPDATE_ALL=OFF
    - name: Install mc_rtc and related projects
      shell: bash
      run: |
        cmake --build ${TMPDIR-/tmp}/build-mc-rtc --config RelWithDebInfo
