name: CI Ubuntu Jammy (Devcontainer)

on:
  repository_dispatch:
    types:
    - build-jammy
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  run:
    strategy:
      fail-fast: false
    runs-on: ubuntu-22.04
    steps:
    - name: Maximize build space
      shell: bash
      run: |
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo docker image prune --all --force
    - uses: actions/checkout@v3
      with:
        submodules: recursive
          
#    Install docker (depends on CI Provider)
#    Login to docker registry docker login ghcr.io (or whatever you use)
#    Download DevPod CLI curl -L -o devpod "https://github.com/loft-sh/devpod/releases/latest/download/devpod-linux-amd64" && sudo install -c -m 0755 devpod /usr/local/bin && rm -f devpod
#    devpod provider add docker
#    devpod build github.com/my-org/my-repo --repository ghcr.io/my-org/my-repo --provider docker

    - name: Install devpod
      shell: bash
      run: curl -L -o devpod "https://github.com/loft-sh/devpod/releases/latest/download/devpod-linux-amd64" && sudo install -c -m 0755 devpod /usr/local/bin && rm -f devpod
    - name: Add docker provider 
      shell: bash
      run: devpod provider add docker 
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: arntanguy 
        password: ${{ secrets.GITHUB_TOKEN }}
        logout: false
    - name: Build devcontainer
      shell: bash
      # Prebuild the docker image for github.com/my-org/my-repo and save it in image registry ghcr.io/my-org/my-repo
      run: devpod build . --devcontainer-path ./devcontainer/ubuntu-22.04/devcontainer.json --repository ghcr.io/mc-rtc/mc-rtc-superbuild
